channels:
  - conda-forge
dependencies:
  - jupyter-server-proxy>=1.4
  - pip
  - websockify
  - pyaml
  - ply
  - matplotlib
  - numpy
  - tornado
  - scipy
  - pillow
  - pyqtgraph
  - pyqt
  - nomkl
  - qscintilla2
  - pip:
      - McStasScript
      - guide_bot
      - .
